#:import MDBoxLayout kivymd.uix.boxlayout.MDBoxLayout
#:import MDLabel kivymd.uix.label.MDLabel

<Mainscreen>
	name: 'main'
	canvas.before:
		Color: 
			rgba: 0.1, 0.6, 0.55, 1
		Rectangle: 
			pos: self.pos
			size: self.size

	MDBoxLayout:

		orientation: 'vertical'
		padding: dp(20)
		spacing: dp(20)

		MDLabel:
			text: 'Password Safe'
			halign: 'center'
			theme_text_color: 'Primary'
			#font_style: "H4"